<a href="https://colab.research.google.com/github/angelgmangalan/test/blob/main/SPRAG_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***This is the Question dataset in which Question ID, Question, Question type (like explain, define) and reference answers are given***

Data

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/Question_data.csv")
print(df)

     QuestionID                                       QuestionText  \
0    PythonQ001  Write down the mutable data structures in Python?
1    PythonQ002                                 Define a function?
2    PythonQ003  What is the difference between list and tuple ...
3    PythonQ004  What is the difference between local variable ...
4    PythonQ005  Write a python function to find the sum of ele...
..          ...                                                ...
109  BasicML044  What are the different plots used for doing Un...
110  BasicML045                             Write about Histogram.
111  BasicML046                       write about isnull() method.
112  BasicML047                          Write about Nominal data?
113  BasicML049             Write about train_test_split() method.

    QuestionType                                   Reference Answer
0        Explain  List, Set and Dictionary are mutable data stru...
1         Define  A function is a  reusable block of code that i...
2     Difference  List and tuple differ in mutability. List is m...
3     Difference  Local and global variable differ scope. The sc...
4       Remember                            By using sum() function
..           ...                                                ...
109     Remember  Scatter Plot, Line Plot, Strip plot, Swarm Plo...
110      Explain  A histogram is basically used to represent dat...
111      Explain  isnull() method is used to check and manage NU...
112      Explain  Nominal data is data that can be labelled or c...
113      Explain  train_test_split() is a method of sklearn mode...

[114 rows x 4 columns]

In [ ]:
print(df.columns)

Index(['QuestionID', 'QuestionText', 'QuestionType', 'Reference Answer'], dtype='object')

In [ ]:
print(df.shape)

(114, 4)

In [ ]:
print(df.describe)

<bound method NDFrame.describe of      QuestionID                                       QuestionText  \
0    PythonQ001  Write down the mutable data structures in Python?
1    PythonQ002                                 Define a function?
2    PythonQ003  What is the difference between list and tuple ...
3    PythonQ004  What is the difference between local variable ...
4    PythonQ005  Write a python function to find the sum of ele...
..          ...                                                ...
109  BasicML044  What are the different plots used for doing Un...
110  BasicML045                             Write about Histogram.
111  BasicML046                       write about isnull() method.
112  BasicML047                          Write about Nominal data?
113  BasicML049             Write about train_test_split() method.

    QuestionType                                   Reference Answer
0        Explain  List, Set and Dictionary are mutable data stru...
1         Define  A function is a  reusable block of code that i...
2     Difference  List and tuple differ in mutability. List is m...
3     Difference  Local and global variable differ scope. The sc...
4       Remember                            By using sum() function
..           ...                                                ...
109     Remember  Scatter Plot, Line Plot, Strip plot, Swarm Plo...
110      Explain  A histogram is basically used to represent dat...
111      Explain  isnull() method is used to check and manage NU...
112      Explain  Nominal data is data that can be labelled or c...
113      Explain  train_test_split() is a method of sklearn mode...

[114 rows x 4 columns]>

In [ ]:
missing_values = df.isnull().sum().sum()
print(missing_values)

1

In [ ]:
df[df.isnull().any(axis=1)]

,QuestionID,QuestionText,QuestionType,Reference Answer
20,PythonQ021,Iterative functions perform better than Recurs...,NaN,"There will be more number of function calls, a..."

***Answers given by the students and scores (PyResponses) Python questinos are there in this***

In [ ]:
import pandas as pd
df1 = pd.read_csv("/content/PyResponses.csv")
print(df1)

      QuestionID                                      StudentAnswer  Score1  \
0     PythonQ028                                                  -       0
1     PythonQ057                                 No answer for this       0
2     PythonQ027   An interpreter produces a result from a progr...       0
3     PythonQ045    count() method gives Repeated elements ina list       0
4     PythonQ037   During Function definition we mention the par...       1
...          ...                                                ...     ...
2924  PythonQ007  Yes, it is required. It specifies to which blo...       5
2925  PythonQ040  yes, we can assign a default value to a formal...       5
2926  PythonQ040  yes, we can assign default values to formal pa...       5
2927  PythonQ007  yes,it specifies the indentation level i.e up ...       5
2928  PythonQ007  Yes. It indicates the block of code. \nFor eg:...       5

      Score2
0          0
1          0
2          0
3          0
4          0
...      ...
2924       5
2925       5
2926       5
2927       5
2928       5

[2929 rows x 4 columns]

In [ ]:
print(df1.shape)

(2929, 4)

In [ ]:
print(df1.columns)

Index(['QuestionID', 'StudentAnswer', 'Score1', 'Score2'], dtype='object')

In [ ]:
print(df1.info)

<bound method DataFrame.info of       QuestionID                                      StudentAnswer  Score1  \
0     PythonQ028                                                  -       0
1     PythonQ057                                 No answer for this       0
2     PythonQ027   An interpreter produces a result from a progr...       0
3     PythonQ045    count() method gives Repeated elements ina list       0
4     PythonQ037   During Function definition we mention the par...       1
...          ...                                                ...     ...
2924  PythonQ007  Yes, it is required. It specifies to which blo...       5
2925  PythonQ040  yes, we can assign a default value to a formal...       5
2926  PythonQ040  yes, we can assign default values to formal pa...       5
2927  PythonQ007  yes,it specifies the indentation level i.e up ...       5
2928  PythonQ007  Yes. It indicates the block of code. \nFor eg:...       5

      Score2
0          0
1          0
2          0
3          0
4          0
...      ...
2924       5
2925       5
2926       5
2927       5
2928       5

[2929 rows x 4 columns]>

In [ ]:
missing_values = df1.isnull().sum().sum()
print(missing_values)

5

In [ ]:
df1[df1.isnull().any(axis=1)]

      QuestionID StudentAnswer  Score1  Score2
2708  PythonQ046           NaN       5       5
2709  PythonQ046           NaN       5       5
2710  PythonQ046           NaN       5       5
2711  PythonQ046           NaN       5       5
2713  PythonQ046           NaN       5       5

***For MLResponses - this is dataset for questions related to Machine Learning (Machine learning questions are there in this dataset)***

In [ ]:
import pandas as pd
df2 = pd.read_csv("/content/MLResponses.csv")
print(df2)

      QuestionID                                      StudentAnswer  Score1  \
0     BasicML045   a graphical representation that organizes a g...       4
1     BasicML042         Accuracy, Recall, Precision, and F1- Score       4
2     BasicML044     Box plot,Histograms,,scatter plot,Violion plot       4
3     BasicML037   Box plot,Histograms,,scatter plot,Violion plot .       5
4     BasicML034   Box plots give a good graphical image of the ...       3
...          ...                                                ...     ...
1105  BasicML002  Yes. Because it is good for beginners .all the...       4
1106  BasicML040          Yes. First matplotlib should be installed       4
1107  BasicML040  Yes. Seaborn is also a Python library used for...       5
1108  BasicML002  Yes.Because it provide lot of courses, computa...       3
1109  BasicML010  You can use the drop function to delete rows a...       5

      Score2
0          3
1          4
2          4
3          5
4          3
...      ...
1105       3
1106       4
1107       5
1108       2
1109       5

[1110 rows x 4 columns]

In [ ]:
print(df.shape)

(114, 4)

In [ ]:
print(df2.columns)

Index(['QuestionID', 'StudentAnswer', 'Score1', 'Score2'], dtype='object')

In [ ]:
print(df2.info)

<bound method DataFrame.info of       QuestionID                                      StudentAnswer  Score1  \
0     BasicML045   a graphical representation that organizes a g...       4
1     BasicML042         Accuracy, Recall, Precision, and F1- Score       4
2     BasicML044     Box plot,Histograms,,scatter plot,Violion plot       4
3     BasicML037   Box plot,Histograms,,scatter plot,Violion plot .       5
4     BasicML034   Box plots give a good graphical image of the ...       3
...          ...                                                ...     ...
1105  BasicML002  Yes. Because it is good for beginners .all the...       4
1106  BasicML040          Yes. First matplotlib should be installed       4
1107  BasicML040  Yes. Seaborn is also a Python library used for...       5
1108  BasicML002  Yes.Because it provide lot of courses, computa...       3
1109  BasicML010  You can use the drop function to delete rows a...       5

      Score2
0          3
1          4
2          4
3          5
4          3
...      ...
1105       3
1106       4
1107       5
1108       2
1109       5

[1110 rows x 4 columns]>

In [ ]:
missing_values = df2.isnull().sum().sum()
print(missing_values)

2

In [ ]:
df2[df2.isnull().any(axis=1)]

     QuestionID StudentAnswer  Score1  Score2
676  BasicML014           NaN       0       0
677  BasicML020           NaN       0       0